### PR TITLE
styled enter high score and condition pages

### PR DESCRIPTION
**Pull request by RyanTG**
and also styled the edit location view.

For my records, I next want to work on the "spinner" style on the edit location page. Currently, if I add a background color, the down arrow disappears. Try something like this, perhaps: http://stackoverflow.com/a/34647870

### CODE REVIEW

**Comment by RyanTG** [comment]
Styled the other form pages. 

Next need to style the Sign Up page.

**Comment by RyanTG** [comment]
The input boxes on the login page weren't consistent with the others.

How do you think the various "suggest" pages look? I think the forms are looking good. I think the whole app is looking good!

**Comment by RyanTG** [comment]
Styled the Sign Up page. But I'm having trouble testing to see how it looks. The app force closes when I click "not a user? sign up." I might be having a gradle issue. Right now gradle is completing in like 8 seconds. That seems wrong!

**Comment by scottwainstock** [comment]
The sign-up page isn't working yet, so that doesn't surprise me. I'll work
on it next.

**Comment by RyanTG** [comment]
Ah ok. I thought that might have been the case, but wasn't sure.

**Comment by scottwainstock** [comment]
Looks great!

**Pull request merged**
