### PR TITLE
some styling for profile

### PR DESCRIPTION
**Pull request by RyanTG**
Not much. But a start.

Since the values are within the same element as the description (like in "5 machines added" the 5 can't be styled separately than the "machines added"), that kind of limits how much I can do.

### CODE REVIEW

**Comment by scottwainstock** [comment]
Do you want me to move them to different elements?

**Comment by RyanTG** [comment]
That would be cool, if it's not a hassle for you.

**Comment by scottwainstock** [comment]
@RyanTG This is not a problem.

**Comment by scottwainstock** [comment]
@RyanTG 430ec1f49955bff39d7b1c39014d14ec4cbb27de

**Pull request merged**
