### PR TITLE
Two commits

### PR DESCRIPTION
**Pull request by RyanTG**
Not totally settled on the profile page format. I don't really like how those last two items look. Something looks off about "Locations Edited:" and "High Scores:"

I think there are still scrolling issues on that page. I only ever see one location that I've edited.

Second commit adds a custom listview. All I did on the custom listview was bump up the font size and added some additional margins. It seems to work fine. However, the scrolling behavior on the profile view MAY have changed after I added it. I'm not certain, though.

### CODE REVIEW

**Comment by RyanTG** [comment]
Tell me what you think of the new launcher logo. I tried to make it fix with the new Android design guidelines. The one REALLY annoying thing is that while the image sizes are clearly specified, the sizes for the actual graphic within the image (like, how much buffer space is around the icon) is not. That's why so many Android icons are totally different sizes. When I used the Android Image Asset Studio (built into AS), there was way too much padding around the icon, and it looked small. Smaller even than the official google app icons! The benefit of the asset studio is that it automatically adds a small drop shadow to the bottom. So I had to make that part myself. I compared it with lots of app icons on the desktop, and it seems to fit in there alright.

Another commit is coming shortly, for action bar icons.

**Comment by RyanTG** [comment]
Using newer icons, taken from https://design.google.com/icons/
Most of these are already in the asset library, so I just imported them, which adds the correct resolutions. I also changed the colors of them.

This is still a little bit of a work in progress. But I think it's a nice improvement! All in all, this batch of commits make some pretty substantial style changes. I think the new buttons look way nicer. I think I was over-designing them before. Now I made them look nearly like the stock buttons, but with the new light blue color.

TODO: The Search icon is not showing up. I think it's because of this: https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/res/menu/map_menu.xml#L6
I'll look into it.

Also TODO: The trash icon is a little small. That's a brand new google icon, so I took it from the site and it seems to have different padding around it, resulting in a smaller icon.

Also TODO: In the actionbar, the old PBM icon is still there. I want to replace it with the new one. But I didn't see an obvious place to do that. So I'll look deeper.

Sometimes the search function in AS kind of sucks. It doesn't find things that I KNOW are there.

**Comment by scottwainstock** [comment]
@RyanTG Likin' the new launcher, yeah. Cool 3d fx.

**Comment by RyanTG** [comment]
You can ignore that question. It doesn't seem worth the effort. I don't think the search icon looks great. But it's just way too much effort to override it.

**Pull request merged**
