### PR TITLE
More style updates

### PR DESCRIPTION
**Pull request by RyanTG**
Closes: 
https://github.com/RyanTG/pbm-android/issues/8
https://github.com/RyanTG/pbm-android/issues/9
https://github.com/RyanTG/pbm-android/issues/11
https://github.com/RyanTG/pbm-android/issues/12
https://github.com/RyanTG/pbm-android/issues/13
https://github.com/RyanTG/pbm-android/issues/14
https://github.com/RyanTG/pbm-android/issues/15

One thing I can't figure out: On the location detail page, there's no text in the actionbar (like, it doesn't say the location name). And that's fine. But I wanted to add the new icon to that page. I figured that adding
`getSupportActionBar().setIcon(R.mipmap.ic_launcher);` to https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/LocationDetail.java#L37 would do it. But it doesn't. Some people say that you have to first say "true" to that home back arrow. But that doesn't do it here. Nor do we want that arrow anyway. This isn't a big deal. But it just looks sort of empty up there.

TODO: I'm concerned that the region loading "splash" images are too low res for modern phones. They don't look super crisp. I'm considering scrapping them for something new/simpler. But it might be more work than it's worth at the moment. https://github.com/RyanTG/pbm-android/issues/10

I feel like I'm on a roll with android lately.

### CODE REVIEW

**Comment by RyanTG** [comment]
This - https://github.com/scottwainstock/pbm-android/pull/117/commits/7fb28cc5eb8a09bcccfe4d69369bcaaa04d9b99f - broke the Suggest New Region form. The 'success' toast message still showed up, but the email didn't arrive. So perhaps there's something else along the way checking for name and email and rejected if they aren't present. I reverted that change in the next commit https://github.com/scottwainstock/pbm-android/pull/117/commits/dc131e8b3206db9f5d626611bf42d68a8349bce9

But I didn't revert the removal of those fields from the Contact Admin form, because that one is still going through.

**Comment by RyanTG** [comment]
Closes: 
https://github.com/RyanTG/pbm-android/issues/16
https://github.com/RyanTG/pbm-android/issues/17
https://github.com/RyanTG/pbm-android/issues/18
https://github.com/RyanTG/pbm-android/issues/19
https://github.com/RyanTG/pbm-android/issues/21
https://github.com/RyanTG/pbm-android/issues/22

**Comment by RyanTG** [comment]
This commit - https://github.com/scottwainstock/pbm-android/pull/117/commits/5753bb54d906c08d44c34854bb79338cdb4fbaa5 - ONLY adds a splash screen. It doesn't change the region initializing screen. 

One puzzling thing is that the splash screen occurs before the Regiontab view loads. And that ends up changing some of the style characteristics of the regiontab view (notably, it removes any "default" listview styles - things I hadn't explicitly stated in that xml file - such as text color). That's why the text for the "loading list of regions" is now white. I'll to fix it. That's also why there are no horizontal lines between each region name. Not sure if I can fix that.

Anyway, the goal of this commit is to make it so users don't have to look at a blank white screen while the app loads. Because it takes quite a while to load!

**Comment by RyanTG** [comment]
I still don't really know what to do with the region initializing screen. We only created images that are MDPI, which is way too small for modern phones. Our phones are likely XHDPI or XXHDPI. So those images are pixelated.

When I made the t-shirt graphic, I modified that original initializing image and made it huge. So I guess we can use that! It will look slightly different. That doesn't solve the issue with the region name images, though. We might just have to ditch those. I was originally thinking of adding a simple graphic to that loading screen, and then using text to display the region name. But that might look janky.

**Comment by RyanTG** [comment]
I'm tripping out. BEFORE you pull this, can you tell me if the login and signup pages display the actionbar? Like, on the login page, it says, "Login" on the actionbar? For some reason I don't remember the actionbar being visible on these pages. But now it's there. I don't see how I could have added something like this, though. Guessing it was always there.

**Comment by scottwainstock** [comment]
@RyanTG 
screen shot 2016-10-03 at 7 35 04 pm

**Comment by scottwainstock** [comment]
@RyanTG The "about" page could use some styling...

**Comment by scottwainstock** [comment]
@RyanTG I like the user profile icon thing, that's cool. Splash page didn't come up for me when I first loaded the app... it DID show up when I switched regions though.

**Comment by scottwainstock** [comment]
@RyanTG It DID add a "Pinball Map" actionbar text thing to the loading page after you select a region though... I feel like THAT is new (and probably unnecessary)...

screen shot 2016-10-03 at 8 02 36 pm

**Comment by RyanTG** [comment]
I had trouble testing whether the splash was showing up when first launching because the app wasn't always "cold" launching, even if I'd closed it completely.

I didn't notice those actionbars until one of today's commits (which had to do with splash/initializing screens). I'll take a look at it tomorrow.

Yeah, that About page is loco. I'll work on it.

**Comment by RyanTG** [comment]
Buttons and textboxes on the login page probably don't need to be that humongous, either.

**Comment by RyanTG** [comment]
There's also the chance that there's no "intent" or whatever for the splash screen when the app is first launched. That might be beyond me, though.

**Comment by RyanTG** [comment]
Actually, I think the "Pinball Map" actionbar was already there (even on the initializing screen). But the actionbar was black before, and so I don't think it stood out.

**Pull request merged**
